# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cc164398a08e16145d29cd01c9ecc45eecbf6eeba9144401048f7f8e2bf0cc88e0563cce924cfa3aa5be8b561e404298564127617235c94f6203edb17bdb346

test:
  secret_key_base: 3fa1b9dd617f639d44f71059d2c6767961bbb01b2987237b0557a70dfc881577c904e1c157804fd833286ec919730ed1e57c485c0992d1c20d139cdc82ea9b00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
